;;  (chabam-foreground     "#FFFFFF")
;;  (chabam-background     "#161616")
;;  (chabam-dark-bg        "#000000")
;;  (chabam-dark-grey      "#262626")
;;  (chabam-grey           "#393939")
;;  (chabam-light-grey     "#525252")
;;  (chabam-pink           "#FF74B8")
;;  (chabam-light-pink     "#FF4297")
;;  (chabam-green          "#00C15A")
;;  (chabam-blue           "#00B4FF")
;;  (chabam-light-blue     "#66D1FF")
;;  (chabam-turquoise      "#00dfdb")
;;  (chabam-dark-turquoise "#00c1bb")
;;  (chabam-purple         "#C693FF")
;;  (chabam-blue-bg        "#1d293f")
;;  (chabam-purple-bg      "#554272")
;;  (chabam-orange         "#FF6300")
;;  (chabam-electric-blue  "#0064ff")
;;  )

(deftheme chabam-light
  "My custom inspired by Oxocarbon light mode")

(let (
      (chabam-foreground     "#161616")
      (chabam-background     "#FFFFFF") 
      (chabam-dark-bg        "#000000")
      (chabam-dark-grey      "#262626")
      (chabam-grey           "#393939")
      (chabam-light-grey     "#525252")
      (chabam-pink           "#FF74B8")
      (chabam-light-pink     "#FF4297")
      (chabam-green          "#00C15A")
      (chabam-blue           "#00B4FF")
      (chabam-light-blue     "#66D1FF")
      (chabam-turquoise      "#00dfdb")
      (chabam-dark-turquoise "#00c1bb")
      (chabam-purple         "#C693FF")
      (chabam-blue-bg        "#ddeaff")
      (chabam-purple-bg      "#d8bfff")
      (chabam-orange         "#FF6300")
      (chabam-electric-blue  "#0064ff"))
  (custom-theme-set-variables
   'chabam-light
   '(frame-background mode (quote light)))

  (custom-theme-set-faces
   'chabam-light
   ;; Generic styling
   `(default                      ((t (:foreground ,chabam-foreground :background ,chabam-background))))
   `(region                       ((t (:background ,chabam-blue-bg))))
   `(match                        ((t (:background ,chabam-purple-bg))))
   `(mode-line                    ((t (:foreground ,chabam-background :background ,chabam-electric-blue))))
   `(mode-line-inactive           ((t (:foreground ,chabam-light-grey :background ,chabam-dark-bg))))
   `(line-number                  ((t (:foreground ,chabam-light-grey))))
   `(border                       ((t (:foreground ,chabam-dark-bg))))
   `(cursor                       ((t (:background ,chabam-electric-blue))))

   `(font-lock-builtin-face       ((t (:foreground ,chabam-purple))))
   `(font-lock-comment-face       ((t (:foreground ,chabam-light-grey))))
   `(font-lock-string-face        ((t (:foreground ,chabam-green))))
   `(font-lock-type-face          ((t (:foreground ,chabam-blue))))
   `(font-lock-function-name-face ((t (:foreground ,chabam-light-blue))))
   `(font-lock-variable-name-face ((t (:foreground ,chabam-light-blue))))
   `(font-lock-keyword-face       ((t (:foreground ,chabam-purple))))
   `(font-lock-constant-face      ((t (:foreground ,chabam-dark-turquoise))))
   `(font-lock-preprocessor-face  ((t (:foreground ,chabam-light-pink))))
   )
  )
    
(provide-theme 'chabam-light)
