(deftheme chabam-dark
  "My custom inspired by Oxocarbon dark mode")

(let (
      (chabam-foreground      "#FFFFFF")
      (chabam-background      "#161616")
      (chabam-dark-bg         "#000000")
      (chabam-dark-grey       "#262626")
      (chabam-grey            "#393939")
      (chabam-light-grey      "#525252")
      (chabam-light-pink      "#FF74B8")
      (chabam-pink            "#FF4297")
      (chabam-green           "#00C15A")
      (chabam-blue            "#00B4FF")
      (chabam-light-blue      "#66D1FF")
      (chabam-turquoise       "#00dfdb")
      (chabam-dark-turquoise  "#00c1bb")
      (chabam-purple          "#C693FF")
      (chabam-blue-bg         "#1d293f")
      (chabam-purple-bg       "#554272")
      (chabam-orange          "#FF6300")
      (chabam-electric-blue   "#0064ff")
      (chabam-red             "#990000")
      (adwaita-black          "#241f31")
      (adwaita-red            "#c01c28")
      (adwaita-green          "#2ec27e")
      (adwaita-yellow         "#f5c211")
      (adwaita-blue           "#1e78e4")
      (adwaita-magenta        "#9841bb")
      (adwaita-cyan           "#0ab9dc")
      (adwaita-grey           "#c0bfbc")
      (adwaita-bright-black   "#5e5c64")
      (adwaita-bright-red     "#ed333b")
      (adwaita-bright-green   "#57e389")
      (adwaita-bright-yellow  "#f8e45c")
      (adwaita-bright-blue    "#51a1ff")
      (adwaita-bright-magenta "#c061cb")
      (adwaita-bright-cyan    "#4fd2fd")
      (adwaita-bright-grey    "#f6f5f4")
      )

  (custom-theme-set-variables
   'chabam-dark
   '(frame-background mode (quote dark)))


  (custom-theme-set-faces
   'chabam-dark
   ;; Generic styling
   `(default                            ((t (:foreground ,chabam-foreground :background ,chabam-background))))
   `(highlight                          ((t (:background ,chabam-purple-bg))))
   `(region                             ((t (:background ,chabam-dark-grey))))
   `(match                              ((t (:background ,chabam-purple-bg))))
   `(mode-line                          ((t (:foreground ,chabam-foreground :background ,chabam-electric-blue))))
   `(mode-line-inactive                 ((t (:foreground ,chabam-light-grey :background ,chabam-dark-bg))))
   `(line-number                        ((t (:foreground ,chabam-light-grey :inherit default))))
   `(border                             ((t (:foreground ,chabam-dark-bg))))
   `(vertical-border                    ((t (:foreground ,chabam-dark-bg))))
   `(cursor                             ((t (:background ,chabam-pink))))
   `(fringe                             ((t (:background ,chabam-background))))
   `(minibuffer-prompt                  ((t (:foreground ,chabam-purple))))
   `(lazy-highlight                     ((t (:background ,chabam-blue-bg))))
   `(isearch                            ((t (:background ,chabam-purple-bg))))
   `(isearch-fail                       ((t (:background ,chabam-red))))
   `(query-replace                      ((t (:background ,chabam-purple-bg))))
   `(show-paren-match                   ((t (:foreground ,chabam-pink :bold t))))
   `(show-paren-mismatch                ((t (:foreground ,chabam-red :bold t))))
   `(button                             ((t (:foreground ,chabam-blue :underline t))))
   `(warning                            ((t (:foreground ,adwaita-yellow))))
   `(error                              ((t (:foreground ,adwaita-red))))
   `(ansi-color-black                   ((t (:foreground ,adwaita-black))))
   `(ansi-color-red                     ((t (:foreground ,adwaita-red))))
   `(ansi-color-blue                    ((t (:foreground ,adwaita-blue))))
   `(ansi-color-cyan                    ((t (:foreground ,adwaita-cyan))))
   `(ansi-color-green                   ((t (:foreground ,adwaita-green))))
   `(ansi-color-yellow                  ((t (:foreground ,adwaita-yellow))))
   `(ansi-color-magenta                 ((t (:foreground ,adwaita-magenta))))
   `(ansi-color-bright-black            ((t (:foreground ,adwaita-bright-black))))
   `(ansi-color-bright-red              ((t (:foreground ,adwaita-bright-red))))
   `(ansi-color-bright-blue             ((t (:foreground ,adwaita-bright-blue))))
   `(ansi-color-bright-cyan             ((t (:foreground ,adwaita-bright-cyan))))
   `(ansi-color-bright-green            ((t (:foreground ,adwaita-bright-green))))
   `(ansi-color-bright-yellow           ((t (:foreground ,adwaita-bright-yellow))))
   `(ansi-color-bright-magenta          ((t (:foreground ,adwaita-bright-magenta))))

   ;; Help styling
   `(help-key-binding                   ((t (:foreground ,chabam-dark-turquoise :background ,chabam-dark-bg, :bold t))))
   `(trailing-whitespace                ((t (:background ,chabam-red))))
   `(link                               ((t (:foreground ,chabam-light-blue :underline t))))
   `(visited-link                       ((t (:foreground ,chabam-purple :underline t))))
   `(eldoc-highlight-function-argument  ((t (:inherit isearch :bold t))))

   ;; Programming syntax styling
   `(font-lock-builtin-face             ((t (:foreground ,chabam-purple))))
   `(font-lock-comment-face             ((t (:foreground ,chabam-light-grey))))
   `(font-lock-string-face              ((t (:foreground ,chabam-green))))
   `(font-lock-type-face                ((t (:foreground ,chabam-blue))))
   `(font-lock-function-name-face       ((t (:foreground ,chabam-light-blue))))
   `(font-lock-variable-name-face       ((t (:foreground ,chabam-light-blue))))
   `(font-lock-keyword-face             ((t (:foreground ,chabam-purple))))
   `(font-lock-constant-face            ((t (:foreground ,chabam-dark-turquoise))))
   `(font-lock-warning-face             ((t (:foreground ,adwaita-yellow))))

   ;; 1st party styling
   `(dired-header                       ((t (:foreground ,chabam-blue))))
   `(dired-directory                    ((t (:foreground ,chabam-dark-turquoise))))
   `(dired-symlink                      ((t (:foreground ,chabam-light-pink))))
   `(apropos-symbol                     ((t (:foreground ,chabam-pink))))
   `(flymake-error                      ((t (:underline (:style line :color ,chabam-red)))))
   `(flymake-warning                    ((t (:underline (:style line :color ,adwaita-yellow)))))
   `(flymake-note                       ((t (:underline (:style line :color ,chabam-blue)))))
   `(flymake-error-echo                 ((t (:foreground ,adwaita-red))))
   `(flymake-warning-echo               ((t (:foreground ,adwaita-yellow))))
   `(flymake-note-echo                  ((t (:foreground ,chabam-blue))))
   `(eglot-highlight-symbol-face        ((t (:inherit region))))
   `(xref-file-header                   ((t (:foreground ,chabam-turquoise))))
   `(compilation-info                   ((t (:foreground ,chabam-turquoise))))
   `(xref-file-header                   ((t (:foreground ,chabam-turquoise))))


   ;; 3rd party styling
   `(vertico-current                    ((t (:background ,chabam-dark-grey))))
   `(completions-common-part            ((t (:foreground ,chabam-dark-turquoise))))
   `(orderless-match-face-0             ((t (:inherit completions-common-part))))
   `(git-gutter:added                   ((t (:foreground ,chabam-green))))
   `(git-gutter:removed                 ((t (:foreground ,chabam-red))))
   `(git-gutter:modified                ((t (:foreground ,chabam-light-blue))))
   `(corfu-bar                          ((t (:background ,chabam-grey))))
   `(corfu-default                      ((t (:foreground ,chabam-foreground :background ,chabam-dark-bg))))
   `(corfu-border                       ((t (:background ,chabam-dark-bg))))
   `(corfu-current                      ((t (:inherit vertico-current))))
 ))

(provide-theme 'chabam-dark)
