name: Automated system update

on:
  schedule:
    - cron: "0 0 * * Sun"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v20

      - run: nix flake update

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: System update
          branch: main
          commit_options: '--no-verify --signoff'
          file_pattern: flake.lock
          skip_dirty_check: false
          skip_fetch: true
